#!/usr/bin/env python
"""
Solve Squaredle puzzles, main entry point.

(c) Robert Rainthorpe 2023
"""

from pysquaredle.helpers import parse_args, puzzle_letters, shuffle
from pysquaredle.puzzle import Puzzle
from pysquaredle.solver import Solver
from pysquaredle.ui.application import Application


def main() -> int:
    """
    Main entry point for pysquaredle. Solves or sets Squaredle-type puzzles.

    If the --gui flag is set, the GUI is launched.
    """

    args = parse_args()

    letters = puzzle_letters(args)

    if args.random:
        letters = shuffle(letters)

    puzzle = Puzzle(letters)

    if args.slow_mode:

        def report(word: str, chain: list[int], hit_count: int) -> None:
            print(f"Checking {word} at {chain}. Hits: {hit_count}")

        solver = Solver(puzzle, args.file, report)
    else:
        solver = Solver(puzzle, args.file)

    if args.debug:
        print(puzzle.list_neighbours)

    if args.gui:
        app = Application(puzzle, solver, args.sort, args.multiple)
        return app.exec()

    if args.grid or args.random or args.square or args.auto_extend:
        print(puzzle.grid)

    print(
        solver.formatted_solutions(
            alpha_sort=args.sort,
            length_group=args.length,
            headers=args.headers,
            single_column=args.single_column,
        )
    )

    # be nice to pipelines
    return 0


if __name__ == "__main__":
    main()
