# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Preferences:
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(540, 480)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Preferences.sizePolicy().hasHeightForWidth())
        Preferences.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setGeometry(QtCore.QRect(180, 440, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.checkBox = QtWidgets.QCheckBox(Preferences)
        self.checkBox.setGeometry(QtCore.QRect(50, 30, 131, 20))
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(Preferences)
        self.label.setGeometry(QtCore.QRect(70, 60, 321, 41))
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Preferences)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 130, 441, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.colorChooser = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.colorChooser.setContentsMargins(0, 0, 0, 0)
        self.colorChooser.setObjectName("colorChooser")
        self.label_2 = QtWidgets.QLabel(Preferences)
        self.label_2.setGeometry(QtCore.QRect(67, 210, 411, 41))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Preferences)
        self.buttonBox.accepted.connect(Preferences.accept)  # type: ignore
        self.buttonBox.rejected.connect(Preferences.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Preferences"))
        self.checkBox.setText(_translate("Preferences", "Multiple Solutions"))
        self.label.setText(
            _translate(
                "Preferences",
                "Show all the solutions for a given word. Can get messy or colourful",
            )
        )
        self.label_2.setText(
            _translate(
                "Preferences",
                "The colours above are used for solution lines, in order from top-left to bottom-right. Choose a colour to edit it.",
            )
        )
